
name: Hello NueXini

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration File'
        required: true
        default: 'xiaomi_mi-router-3g.config'
      source:
        description: 'Git Source'
        required: true
        default: '1'

jobs:
  build:
    name: ${{ github.event.inputs.config }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -y update 2>&1 >/dev/null
        sudo -E apt-get -y install $(cat ./.github/workflows/BuildEnviroment) 2>&1 >/dev/null
        sudo -E apt-get -y autoremove --purge 2>&1 >/dev/null
        sudo -E apt-get -y clean 2>&1 >/dev/null

    - name: Git Clone
      run: |
        chmod +x $GITHUB_WORKSPACE/Z.Backup/sh/*.sh
        chmod +x $GITHUB_WORKSPACE/Z.Backup/scripts/*.sh
        
        releasetag=$(sed -n "${{ github.event.inputs.source }}p" $GITHUB_WORKSPACE/Z.Backup/list/releasetag.list)
        git clone $releasetag nuexini
    
    - name: Feeds
      run: |
        cd nuexini
        echo 'src-git NueXini_Packages https://github.com/NueXini/NueXini_Packages.git' >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    
    - name: Patch
      run: |
        cd nuexini
        cp -f $GITHUB_WORKSPACE/Z.Backup/config/${{ github.event.inputs.config }} .config
        bash $GITHUB_WORKSPACE/Z.Backup/sh/Hi_NueXini.sh
        
        make defconfig
        make download -j8
        rm -rf $(find ./dl/ -size -1024c)
        
    - name: Build
      run: |
        cd nuexini
                
        make -j8 || make -j1 V=sc > ./make-error.log 2>&1
        
        mkdir -p ./artifact/firmware
          
        bash $GITHUB_WORKSPACE/Z.Backup/scripts/firmware.sh

    - name: Upload error log
      uses: actions/upload-artifact@master
      if: failure()
      with:
        name: build-failure-log
        path: nuexini/make-error.log
    
    - name: Upload Firmware
      uses: actions/upload-artifact@master
      with:
        name: ${{ github.event.inputs.config }}-Firmware
        path: nuexini/artifact/firmware

