
name: Hi NueXini

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration File'
        required: true
        default: 'xiaomi_mi-router-3g.config'
      source:
        description: 'Git Source'
        required: true
        default: '1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Build
      run: |
        chmod +x $GITHUB_WORKSPACE/Z.Backup/sh/*.sh
        chmod +x $GITHUB_WORKSPACE/Z.Backup/scripts/*.sh
        
        releasetag=$(sed -n "${{ github.event.inputs.source }}p" $GITHUB_WORKSPACE/Z.Backup/config/releasetag.list)
        git clone $releasetag dd
        
        cd dd
        mkdir -p ./nuexini
        
        echo 'src-git NueXini_Packages https://github.com/NueXini/NueXini_Packages.git' >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
        cp -rf $GITHUB_WORKSPACE/Z.Backup/config/${{ github.event.inputs.config }} .config
        
        bash $GITHUB_WORKSPACE/Z.Backup/sh/Hi_NueXini.sh
        
        ln -sf $GITHUB_WORKSPACE/Z.Backup/scripts/makemenuconfig.sh ./mk.sh
        ln -sf $GITHUB_WORKSPACE/Z.Backup/scripts/cpcfg.sh ./cp.sh
        ln -sf $GITHUB_WORKSPACE/Z.Backup/scripts/dd.sh ./dd.sh
        
    - name: Hi NueXini
      uses: klever1988/ssh2actions@main
      
    - name: Preparation
      run: |
        cd dd
        bash dd.sh

    - name: Last thing
      uses: actions/upload-artifact@master
      with:
        name: config
        path: dd/nuexini

###### ###### ###### ###### ###### 
#    - name: Hi NueXini
#      uses: rdp-studio/ssh2actions@v2.0.0
#      with:
#        mode: ngrok
#      env:
#        SSH_PASSWORD: 'nuexini'
#        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
