
name: Hi NueXini

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration File'
        required: true
        default: 'xiaomi_mi-router-3g.config'
      source:
        description: 'Git Source'
        required: true
        default: '1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Build
      run: |
        chmod +x $GITHUB_WORKSPACE/Z.Backup/sh/*.sh
        chmod +x $GITHUB_WORKSPACE/Z.Backup/scripts/*.sh
        
        releasetag=$(sed -n "${{ github.event.inputs.source }}p" $GITHUB_WORKSPACE/Z.Backup/config/releasetag.list)
        git clone $releasetag dd
        
        cd dd
        mkdir -p ./nuexini
        
        /bin/bash $GITHUB_WORKSPACE/Z.Backup/sh/Hello_NueXini.sh
        
        ./scripts/feeds update -a > /dev/null
        ./scripts/feeds install -a > /dev/null
        
        cp -rf $GITHUB_WORKSPACE/Z.Backup/config/${{ github.event.inputs.config }} .config
        
        /bin/bash $GITHUB_WORKSPACE/Z.Backup/sh/Hi_NueXini.sh
        
        ln -sf $GITHUB_WORKSPACE/Z.Backup/scripts/makemenuconfig.sh ./dd2.sh
        ln -sf $GITHUB_WORKSPACE/Z.Backup/scripts/cpcfg.sh ./dd3.sh
        
        echo "grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > NX_DEVICE_NAME" > dd.sh
        echo 'cp -rf ./.config ./nuexini/$(cat NX_DEVICE_NAME).config' >> dd.sh
        
    - name: Hi NueXini
      uses: klever1988/ssh2actions@main
      
    - name: Preparation
      run: |
        cd dd
        /bin/bash dd.sh

    - name: Last thing
      uses: actions/upload-artifact@master
      with:
        name: config
        path: dd/nuexini

###### ###### ###### ###### ###### 
#    - name: Hi NueXini
#      uses: rdp-studio/ssh2actions@v2.0.0
#      with:
#        mode: ngrok
#      env:
#        SSH_PASSWORD: 'nuexini'
#        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
