
name: NueXini

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Git Source'
        required: true
        default: '1'
        
jobs:
  Fconfig: 
    name: Generate Config
    runs-on: ubuntu-latest
    outputs:
      CFG_CONFIG: ${{ steps.findconfig.outputs.CFG_CONFIG }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Find Config
        id: findconfig
        run: |
          CFGS="$(cat $GITHUB_WORKSPACE/Z.Backup/list/cfg.list)"
          
          NUEXINI='['
          n=1
          
          for a in $CFGS; do
            [[ $n -ne 1 ]] && NUEXINI="$NUEXINI"','
            NUEXINI="$NUEXINI"'"'"${a}"'"'
            n=0
          done
          
          NUEXINI="$NUEXINI"']'
          
          echo $NUEXINI
          echo "::set-output name=CFG_CONFIG::$NUEXINI"
  
  build:
    name: ${{ matrix.config }}
    needs: [Fconfig]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        config: ${{fromJson(needs.Fconfig.outputs.CFG_CONFIG)}}

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -y update 2>&1 >/dev/null
          sudo -E apt-get -y install $(cat ./.github/workflows/BuildEnviroment) 2>&1 >/dev/null
          sudo -E apt-get -y autoremove --purge 2>&1 >/dev/null
          sudo -E apt-get -y clean 2>&1 >/dev/null
      
      - name: Git Clone
        run: |
          chmod +x $GITHUB_WORKSPACE/Z.Backup/sh/*.sh
          chmod +x $GITHUB_WORKSPACE/Z.Backup/scripts/*.sh
          
          releasetag=$(sed -n "${{ github.event.inputs.source }}p" $GITHUB_WORKSPACE/Z.Backup/list/releasetag.list)
          git clone $releasetag nuexini
        
      - name: Feeds
        run: |
          cd nuexini
          echo 'src-git NueXini_Packages https://github.com/NueXini/NueXini_Packages.git' >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Configure .config
        run: |
          cd nuexini
          cp -f $GITHUB_WORKSPACE/Z.Backup/config/${{ matrix.config }} .config
          
          bash $GITHUB_WORKSPACE/Z.Backup/sh/Hi_NueXini.sh
          
      - name: Parse toolchain file
        run: |
          cd nuexini
          grep '^CONFIG_TARGET_BOARD' .config | cut -d '"' -f 2 >NX_TARGET_BOARD
          grep '^CONFIG_TARGET_SUBTARGET' .config | cut -d '"' -f 2 >NX_TARGET_SUBTARGET
          curl -s "https://downloads.cdn.openwrt.org/snapshots/targets/$(cat NX_TARGET_BOARD)/$(cat NX_TARGET_SUBTARGET)/sha256sums" \
            | sed -n -e 's/.*\(openwrt-toolchain.*\).tar.xz/\1/p' >NX_TOOLCHAIN_FILE
          cat NX_SDK_FILE
            
      - name: Download toolchain
        run: |
          cd nuexini
          wget -q -O - https://downloads.cdn.openwrt.org/snapshots/targets/$(cat NX_TARGET_BOARD)/$(cat NX_TARGET_SUBTARGET)/$(cat NX_TOOLCHAIN_FILE).tar.xz \
            | tar --xz -xf -
        
      - name: Configure external toolchain
        run: |
          cd nuexini
          bash ./scripts/ext-toolchain.sh \
            --toolchain $(cat NX_TOOLCHAIN_FILE)/toolchain-* \
            --overwrite-config \
            --config $(cat NX_TARGET_BOARD)/$(cat NX_TARGET_SUBTARGET)
          
          make defconfig
          make download -j8
          rm -rf $(find ./dl/ -size -1024c)
          
      - name: Build toolchain
        run: |
          cd nuexini
          make toolchain/install -j$(nproc)
        
      - name: Build
        run: |
          cd nuexini
          
          make -j$(nproc) || make -j1 V=sc > ./make-error.log 2>&1
          
          mkdir -p ./artifact/firmware
          
          bash $GITHUB_WORKSPACE/Z.Backup/scripts/firmware.sh
    
      - name: Upload error log
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: ${{ matrix.config }}-build-failure-log
          path: nuexini/make-error.log
        
      - name: Upload Firmware
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.config }}
          path: nuexini/artifact/firmware
